import React from "react"
import Layout from "../components/layout";
import Seo from "../components/seo";

const Terms = () => {

  return (
    <Layout>
        <Seo title="Terms" />
        <div className="terms_wrapper">
            <h2>Terms & Conditions</h2>
        <p>These Terms and Conditions of Service and Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”, “your”) and Day Trade Killers, doing business as Dreams Through Knowledge (“Day Trade Killers”, “Dreams Through Knowledge”, “we”, “us”, or “our”), concerning your access to and use of the https://DayTradeKillers.com/ website and discord server, as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively the “Site”). By submitting this form to us, you agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY. YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT ANY ELECTRONICALLY DIGITIZED SIGNATURES YOU PROVIDE ON THIS WEBSITE ARE REPRESENTATIONS OF YOUR SIGNATURE AND ARE LEGALLY VALID AND BINDING AS IF YOU SIGNED THESE TERMS AND CONDITIONS MANUALLY WITH INK ON PAPER. YOU FURTHER AGREE THAT ANY AND ALL ELECTRONICALLY DIGITIZED SIGNATURES PROVIDED ON THIS WEBSITE ARE LEGALLY VALID AND BINDING AS IF THEY WERE ORIGINAL, WET-SIGNED DOCUMENTS. The Site is an online resource related to the trading of securities that provides its customers and members with interactive chat rooms, trading, investment and research tools, and educational classes, materials and resources for use by customers and members in connection with their trading activities. “Securities” as used herein and for the purposes of these Terms and Conditions, shall include but not be limited to, money, securities, commodities and other investments of every kind and nature and all contracts and options relating thereto, whether for present or future delivery. In consideration of each member or customer’s (each, a “customer” or “you“) access to and use of the Site, we require every members and customer to act with integrity, to our rules for the Site, and to abide by these Terms and Conditions and each other rule, regulation or other policy of Day Trade Killers. You agree to read these Terms and Conditions carefully and retain them for future reference. You understand, acknowledge and agree that these Terms and Conditions govern all aspects of my use of the Site and the products and services of Day Trade Killers. By signing these Terms and Conditions and/or using or accessing the Site, you acknowledge that you have received, read and understood these Terms and Conditions and the Privacy Policy of Day Trade Killers. If you are unwilling to be bound by these Terms and Conditions, you will not sign these Terms and Conditions and/or use or access the Site.

GENERAL TERMS

By signing these Terms and Conditions and/or using or accessing the Site, you thereby agree, (a) that you have received, read and understood these Terms and Conditions, and that these Terms and Conditions create a valid and binding agreement, enforceable against you in accordance with the terms hereof, (b) to be bound by these Terms and Conditions, any terms, conditions or other rules, regulations or policies of Day Trade Killers, as each may be amended or supplemented from time to time in our sole discretion without notice, and (c) that your use of the Site shall comply with all applicable federal, state and local laws, rules or regulations, and that you are solely responsible for your compliance with, familiarity with and understanding of any such laws, rules or regulations applicable to your use of the Site. If you do not agree with any portion of these Terms and Conditions, you are prohibited from using or accessing the Site.

Additionally, and without limiting the foregoing, by using or accessing the Site, you represent and warrant to us that you: (a) are eighteen (18) years of age or older, (b) are not currently restricted from using the Site, or not otherwise prohibited from having an account with us, (c) are not a competitor of Day Trade Killers, or engaged in any business or activity, directly or indirectly, that could be competitive with the business or activities of Day Trade Killers, and are not using the Site for any reason that may be in competition with the Site or any other product or service offered by Day Trade Killers, (d) have full power and authority to enter into and perform these Terms and Conditions, and doing so will not violate any other agreement to which you are a party, (e) will not violate any rights of Day Trade Killers, including, without limitation, intellectual property rights such as patent, copyright or trademark rights, and (f) agree to provide, operate and maintain, at your sole risk, cost and expense, all equipment, software, and internet access necessary to use the Site.

Without limiting the generality of the foregoing or any other provision hereof, you acknowledge and agree, as follows:

• Not to solicit login, account or other personal information of another person or request or obtain access to an account of another person;
• Not to bully, intimidate, or harass any person;
• Not to post content that is hateful, threatening, or pornographic, incites violence, or contains nudity, graphic material, gratuitous violence or anything else found to be objectionable by Day Trade Killers in its sole discretion;
• Not to use the Site in any manner that is, or could reasonably be construed to be, unlawful, including, without limitation, in violation of any law, rule or regulation related to securities or investments, or any rules or regulations promulgated by the U.S. Securities and Exchange Commission, and/or rules of any national or other securities exchange and any regulations or other pronouncements having the force of law;
• Not to use the Site in any manner that is, or could reasonably be construed to be, in violation of these Terms and Conditions, fraudulent, misleading, malicious or discriminatory;
• Not to facilitate or encourage any violations of these Terms and Conditions;
• Not to post or make any defamatory, disparaging or false statements, claims or allegations related to the Site, Day Trade Killers, or any other product or service of Day Trade Killers;
• Not to make your account or any portion thereof or the services provided thereby available to the general public or any portion thereof;
• Not to issue chargeback disputes against Day Trade Killers.
• Not to share personal information with members, or request personal information from members.

All content, materials and services related to the Site shall be solely used for, and you hereby agree to solely use it for, your own personal use in connection with your trading activities, and for no other use.

Violating any of the aforementioned will result in immediate removal from Day Trade Killers and forfeits your right to request a refund.

OWNERSHIP; LIMITED LICENSE

By becoming a customer of Day Trade Killers and using the Site, Day Trade Killers hereby grants to you a limited revocable license to use the Site, and its content, materials and services, solely for your personal use and for the purposes set forth on the Site, and subject to these Terms and Conditions and all other rules, regulations and policies imposed or adopted by Day Trade Killers in connection with the Site, which may be amended by Day Trade Killers at any time in its sole discretion and without notice. Such limited revocable license is freely revocable and terminable by Day Trade Killers at any time, without cause and in the sole discretion of Day Trade Killers. Without limiting the foregoing, this limited revocable license shall automatically be revoked and terminated upon any violation of these Terms and Conditions or any other rule, regulation or policy of Day Trade Killers. Upon revocation or termination of this limited revocable license, you shall, and hereby agree to, destroy any materials (electronic or otherwise) related to the Site that remain in your possession or control, and acknowledge that after such revocation or termination Day Trade Killers may deny your access to the Site and any other Day Trade Killers content, materials or services in its sole discretion. Any personal information of a user whose limited revocable license is revoked or terminated by Day Trade Killers will be preserved or disposed of in accordance with the terms of the Privacy Policy of Day Trade Killers. Any information you submit to Day Trade Killers is at your own risk of loss, and Day Trade Killers assumes no liability or responsibility therefor.

Day Trade Killers reserves all rights not expressly granted in these Terms and Conditions, including, without limitation, title, ownership, intellectual property rights, and all other right, title and interest in and to the Site, the products and services of Day Trade Killers, and all related content, materials, services, and other documents, information or items, including any copies or derivative works thereof. You acknowledge and agree that the Site, the products and services of Day Trade Killers, and all related content, materials, services, and other documents, information or items, including any copies or derivative works thereof, is owned by Day Trade Killers, and is protected by copyright, trademark and other intellectual property laws. You further acknowledge and agree that the Site, the products and services of Day Trade Killers and related content, materials, services, and other documents, information or items, including any copies or derivative works thereof, contains certain proprietary data and information of Day Trade Killers, that you will not use this data or information for any unlawful or unauthorized purpose, and that you will use reasonable efforts to protect them from illicit distribution or use.

Additionally, you grant Day Trade Killers an exclusive, irrevocable, worldwide, perpetual, unlimited, freely assignable and sublicenseable, fully paid up and royalty-free right to use, copy, prepare derivative works of, improve, distribute, publish, remove, retain, add, process, analyze and commercialize, in any way now known or in the future discovered, any information, content, ideas, concepts, techniques, data or suggestions submitted to the Site for the purpose of improving or modifying the Site, or any content, materials or services, or for the purpose of creating or developing new content, materials, services or product related to, arising from or ancillary or similar to the Site, without any further consent, notice and/or compensation to you or to any third parties.

VIOLATION; TERMINATION OF ACCOUNT

Day Trade Killers reserves the right to investigate violations of any of these Terms and Conditions or any other policies of Day Trade Killers or the Site, or any other violations of any state, federal or local law, rule or regulation, and to pursue any remedy available to Day Trade Killers whether at law, in equity or otherwise. You hereby acknowledge and agree that Day Trade Killers may notify, involve and cooperate with law enforcement authorities in investigating and prosecuting users who violate these Terms and Conditions or any other policies of Day Trade Killers or the Site, and any other violations of any state, federal or local laws, rules or regulations. You further acknowledge and agree that Day Trade Killers has no obligation to, and does not, screen or monitor any users, information, materials or other content provided or made available through the Site, but has the right to do so at any time in its sole discretion. You further acknowledge and agree that Day Trade Killers may, in its sole discretion, remove or delete any entries, information, materials or other content, and terminate the subscription, membership or account (collectively, your “account”) of any user, that violates these Terms and Conditions or otherwise posts, submits, or disseminates content that Day Trade Killers finds, in its sole discretion, to be objectionable.

You acknowledge and agree that Day Trade Killers may, in its sole discretion, cancel, suspend or terminate your account if you breach these Terms and Conditions. Day Trade Killers may refuse, in its sole discretion, to permit any use of the Site, and may refuse to permit any person to access or use the Site or your account for any reason at any time.

PURCHASES AND REFUNDS

Day Trade Killers offers both individual products for sale and subscription, membership or other periodic fee-based services. For any purchase through the Site, a valid credit card will be required to complete the purchase and the amount of the purchase will be charged to the credit card. 

When purchasing subscription, membership, or other periodic fee-based services on the Site, a valid credit card will be required for billing purposes. You hereby consent to, acknowledge and allow Day Trade Killers to store (or cause a third party to store on behalf of Day Trade Killers) such payment information and agree to the following policies and procedures for payment of subscription, membership, or other periodic fees related to the Site.

Immediately upon signing up for an account or other periodic fee-based services on the Site, the fees associated with the first period or term of your selected account or service (monthly, quarterly, annual, as applicable) will be charged to such credit card. Within ten (10) business days prior to the expiration of the initially selected period or term, and each subsequent such period or term until your account or other periodic service is canceled in accordance with these Terms and Conditions, the fees associated with your selected account or service for the following applicable period or term will be automatically renewed, and an amount for your renewed account or service will be billed and charged to such credit card by Day Trade Killers in accordance with the Site’s then-current pricing schedule. If the credit card associated with your account or service should expire, terminate or any payment is otherwise rejected by the issuing company, Day Trade Killers may immediately terminate your account or service. It is solely your responsibility to ensure (1) that valid credit card information remains on file for your account or service and the automatic renewal thereof, and (2) that a valid email address remains on file for your account or service for any communications from Day Trade Killers related thereto.

Day Trade Killers does not offer and is not required to provide, any refunds or credits for any reason, including, without limitation, satisfaction, or your failure to cancel your account or service prior to its automatic renewal. There is no circumstance in which you will be entitled to, or Day Trade Killers is required to provide, a refund or credit for any reason, including, without limitation, satisfaction, or your failure to cancel your account or service prior to its automatic renewal.

All fees charged by Day Trade Killers in connection with any product purchased or account or service of the Site are exclusive of any taxes, levies, or duties imposed by any taxing authority, and you shall be, and hereby are, responsible for the payment of all such taxes, levies, or duties arising from your purchase of products or use of the Site.

MODIFICATIONS TO THE SITE AND PRICING

Day Trade Killers reserves the right to, and you acknowledge and agree that Day Trade Killers may, modify the Site, including without limitation the content, materials and services offered thereby, and the fees, costs and pricing associated with the Site at any time and without notice. Without limiting the generality of the foregoing, Day Trade Killers reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Site (or any part or portion thereof) without notice. Any new features that augment or enhance the then-current version of the Site, including the release of new tools and resources, shall be subject to these Terms and Conditions and may result, in Day Trade Killers’s sole discretion, to a price increase. Day Trade Killers shall not be liable to you, or to any third party, for any damages, costs, expenses or other liabilities related to any modification, price change, suspension or discontinuance of the Site.
Without limiting the foregoing, Day Trade Killers may use banner notices or similar devices to alert you to certain modifications to the Site or the pricing associated therewith. Alternatively, notice may consist of an email from the Site to an email address associated with your account or service, even if we have other contact information. You also agree that Day Trade Killers may communicate with you through any available means including email, mobile number, telephone, or delivery services, including the postal service, about your account or service or any products or services associated with the Site. You acknowledge and agree that we shall have no liability associated with or arising from your failure to maintain accurate contact or other information, including, but not limited to, your failure to receive critical information about the Site or pricing.

CANCELLATIONS

Your account or service may be cancelled, subject to the terms hereof, at any time; provided that, as set forth above, no refunds will be issued if your account or other periodic fee-based service is cancelled prior to the end of the applicable period or term.

When you cancel, you are solely responsible for properly canceling your account or service. Cancellation requests by telephone, facsimile or other means of communication cannot, and will not, be accepted, honored or effective. The cancellation of your account or service will immediately result in the deactivation and deletion of your account or service, the denial of access to the Site and the forfeiture and relinquishment of all content and information within or related to your account or service. No data, content or information can be recovered once your account or service is cancelled, and you assume all responsibility for preserving any data, content or information on your account or service prior to Day Trade Killers may retain data, content or information from your account after cancellation in backup and/or archival copies of the Site and related databases, but such copies, if any, will not be available to you.

GENERAL DISCLAIMER OF WARRANTIES

THE SITE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH NO WARRANTIES WHATSOEVER.

DAY TRADE KILLERS DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. WITHOUT LIMITING THE FOREGOING, DAY TRADE KILLERS DISCLAIMS ANY WARRANTIES REGARDING THE SECURITY, RELIABILITY, AVAILABILITY, SERVICE LEVELS, TIMELINESS, AND PERFORMANCE OF THE SITE; DAY TRADE KILLERS DISCLAIMS ALL LIABILITY FOR ANY CLAIMS, DAMAGES, LOSSES, COSTS OR EXPENSES (INCLUDING ATTORNEY’S FEES) RELATED TO THE FOLLOWING, AND DOES NOT WARRANT THAT (I) THE SITE WILL MEET YOUR SPECIFIC REQUIREMENTS, (II) THE SITE WILL BE UNINTERRUPTED, TIMELY, AVAILABLE, SECURE OR ERROR-FREE, (III) THAT ANY RESULTS MAY BE OBTAINED FROM YOUR USE OF THE SITE, OR THAT ANY DATA, CONTENT OR INFORMATION ON THE SITE IS, OR WILL BE, VALID, ACCURATE, TIMELY, ADEQUATE, COMPLETE, LEGAL OR OTHERWISE RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SITE WILL MEET YOUR EXPECTATIONS, OR (V) ANY ERRORS IN THE SITE WILL BE CORRECTED.

DAY TRADE KILLERS DISCLAIMS ANY WARRANTIES FOR ANY INFORMATION, CONTENT OR ADVICE OBTAINED THROUGH THE SITE; AND, DAY TRADE KILLERS DISCLAIMS ANY WARRANTIES FOR SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE SITE OR RECEIVED THROUGH ANY LINKS PROVIDED BY THE SITE.

YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SITE, AND ANY CONTENT, SERVICES OR OTHER INFORMATION OR MATERIALS RELATED THERETO, IS SOLELY AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, THAT RESULTS FROM OR ARISES FROM YOUR USE OF THE SITE, OR ANY CONTENT, SERVICES OR OTHER INFORMATION OR MATERIALS RELATED THERETO. YOU HEREBY EXPRESSLY DISCLAIM AND RELEASE AND WAIVE ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, RELATED TO OR ARISING FROM, THE WARRANTIES DISCLAIMED BY DAY TRADE KILLERS  HEREBY.

DISCLAIMERS

DAY TRADE KILLERS EXPRESSLY DISCLAIMS AND DISCLOSES AS FOLLOWS, AND YOU HEREBY CONFIRM THAT YOU UNDERSTAND, ACKNOWLEDGE AND AGREE AS FOLLOWS, AND EXPRESSLY DISCLAIM, RELEASE AND WAIVE ANY LIABILITY, CLAIM, DAMAGES, LOSS, COST OR EXPENSE, INCONSISTENT WITH, RELATED TO OR ARISING FROM THE FOLLOWING:

YOUR RESPONSIBILITY

Day Trade Killers is not registered as an investment adviser with the U.S. Securities and Exchange Commission. Rather, Day Trade Killers relies upon the “publisher’s exclusion” from the definition of “investment adviser” as provided under Section 202(a)(11) (D) of the Investment Advisers Act of 1940 and corresponding state laws. As such, Day Trade Killers does not offer or provide personalized investment advice. To the extent any of the content, material, information and/or any other kind of informational offering published, broadcast, or otherwise stated on this, and/or associated websites, may be deemed to be “investment advice”, such information is impersonal and not tailored to the investment needs of any specific person. The information contained within this, and/or, associated websites, is provided for informational and educational purposes only. The information should not be construed as investment or trading advice, and is not meant to be a solicitation or recommendation to buy, sell, or hold any positions in any indices or financial markets mentioned. The content and information provided by Day Trade Killers, the Site and the other products and services of Day Trade Killers, is solely incidental to the business and activities of Day Trade Killers in providing educational services.

You remain solely responsible for all decisions regarding your purchase and sale of securities, the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter, and all other matters related to your investments and investment strategies. Day Trade Killers does not and will not provide you with any legal, tax, estate planning or accounting advice, or any advice regarding the suitability, profitability or appropriateness for you of any security, investment, financial product, investment strategy or other matter. You understand, acknowledge and agree that Day Trade Killers employees are not authorized to give any such advice, you will neither solicit nor rely on any investment advice from any Day Trade Killers employee. Day Trade Killers recommends that persons desiring to trade or invest in securities do so cautiously and only in consultation with their professional, licensed and qualified financial, legal, tax, estate planning and accounting advisors.

No data, content or information provided by Day Trade Killers, the Site or the other products and services of Day Trade Killers, is intended, and shall not constitute or be construed as, advice or any recommendation to buy or sell securities, nor any offer, or solicitation of an offer, to buy or sell securities, nor an attempt to influence the purchase or sale of any security. Day Trade Killers is not registered as an investment adviser either with the U.S. Securities and Exchange Commission, any other federal or national governmental or regulatory authority, or any state securities governmental or regulatory authority, and the business and activities of Day Trade Killers do not require any such registration.

DATA, CONTENT AND INFORMATION

No data, content or information provided by Day Trade Killers, the Site or the other products and services of Day Trade Killers, is intended, and shall not constitute or be construed as, advice or any recommendation to buy, sell or hold a particular security or pursue any particular investment strategy.

Day Trade Killers neither assumes responsibility for, nor guarantees the accuracy, currency, completeness or usefulness of information, commentary, recommendations, advice, investment ideas or other materials that may be accessed by you through the Site or the other products or services of Day Trade Killers. This includes, without limitation, any forum, chatroom or other online conference, telecast or posting through Day Trade Killers. If you choose to rely on such information, you understand, acknowledge and agree do so solely at your own risk. You understand, acknowledge and agree that the research, analysis, news or other information made available through the Site or the other products or services of Day Trade Killers is not investment advice and is in no way tailored to reflect any personal financial circumstances or investment objectives and the securities and investment strategies discussed may not be suitable for you. Any determination to purchase or sell securities or otherwise invest in securities must be made solely by you after your independent investigation and evaluation thereof based on your personal financials and other circumstances and without any reliance on the data, content or information provided by Day Trade Killers, the Site or the other products and services of Day Trade Killers.

Day Trade Killers cannot, and does not, independently verify, assess or guarantee the validity, adequacy, timeliness, accuracy or completeness of any data, content or information, the suitability or profitability of any particular security or investment, or the potential value of any security, investment or informational source. You bear sole responsibility for your own investment research and decisions, and should seek the advice of a professional, licensed and qualified securities professional before purchasing or selling any security or making any investment.

The forum and chatrooms on the Site are comprised of customers and members (including, without limitation, moderators who are in the employ of Day Trade Killers) posting content and information. All such information and content is for informational purposes only and does not constitute advice or a recommendation by Day Trade Killers to enter into any securities transactions or engage in any of the financial strategies reflected on or suggested in forum and chatrooms (whether such data, content or information is posted by Day Trade Killers or otherwise). Customers and members may write about securities in which they have a financial or other interest, and performance data reflecting other customer’s or member’s holdings may include information about securities not held by Day Trade Killers or its directors, officers, shareholders, employees, agents or affiliates. As such, Day Trade Killers is not responsible for the accuracy of data, content or information or any performance data in any forum or chatroom; and the accuracy of data, content or information or any performance data are not guaranteed, may not be current and should not be relied upon. Nothing in any forum or chatroom is intended as, nor should you rely on it as, investment advice provided by Day Trade Killers or its directors, officers, shareholders, employees, agents or affiliates.

Day Trade Killers does not control, and does not endorse, any data, content or information posted on the forum or chatroom on the Site. You understand, acknowledge and agree that your participation therein is at your own risk, and Day Trade Killers expressly disclaims responsibility for any such data, content or information. Day Trade Killers has the right (but not the obligation) to review and take down any data, content or information. You understand, acknowledge and agree that by accessing the forum or chatroom on the Site, you may be exposed to material that you deem to be offensive, indecent, obscene or otherwise objectionable. Under no circumstances will you hold Day Trade Killers, or its directors, officers shareholders, employees, agents or affiliates, liable for any such content displayed or made available through the Site, or for any loss or damage of any kind incurred as a result of your use of the forum or chatroom on the Site.

Without limiting the generality of the foregoing, you understand, acknowledge and agree that chat room moderators may call out or post both real and hypothetical trades and real and simulated or hypothetical returns for informational and educational purposes only. Moderator commentary is opinion and ideas only and does not constitute any recommendation whatsoever, and you should not relay on such opinions and ideas which may not be complete or accurate. Each of Day Trade Killers’ services, products and site are available for informational and educational purposes only. None of the information contained in the site (which includes, without limitation, our alerts service and chat room) constitutes, or is intended to constitute, a recommendation by us of any particular security or trading strategy or a determination by us that any security or trading strategy is suitable for any specific person. We are publishers and educators only.

You understand, acknowledge and agree that MODERATOR results may be based on simulated or hypothetical performance, and such results have certain inherent limitations. Unlike the results shown in an actual performance record, such results do not represent actual trading. Your actual results may differ from results reported for many reasons, including, without limitation: performance results do not reflect actual trading commissions that You may incur; performance results do not account for the impact, if any, of certain market factors, such as lack of liquidity, that may affect Your results; the investments chosen may be volatile, and server, delivery delays and other factors may cause the price You obtain to differ substantially from the price at the time of the alert; the prices of investments at the point in time You begin subscribing may be higher than such prices at the time such investments were chosen; You may not have the capital to trade as frequently as the moderator; and the size and timing of your purchase or sale of a stock may affect the price of the stock, among other reasons.

You understand, acknowledge and agree that, for informational and teaching purposes only, trades may be called out, posted, or alerted, but not executed. You understand, acknowledge and agree that moderators may sometimes purchase or sell securities sooner or later than called out, posted or alerted. Moderators are also not required to disclose all trades, and their positions may be inconsistent with trades. Also, because some trades may not actually have been executed, results may have under-or-over-compensated for the impact, if any, of certain market factors, such as liquidity. Simulated or hypothetical trading programs in general are also subject to the fact that they are designed with the benefit of hindsight. You understand, acknowledge and agree that the Site contains simulated or hypothetical trading programs. No representation is being made that any account will or is likely to achieve profits or losses similar to these being shown.

You understand, acknowledge and agree that Day Trade Killers and its directors, officers, shareholders, employees, agents and affiliates have no obligation to notify you as to which trades and returns are real versus simulated or hypothetical, and that Day Trade Killers, and its directors, officers, shareholders, employees, agents and affiliates do not verify moderator trade records or maintain records of moderator trades and results, and that moderators have no obligation to provide Day Trade Killers any data.

Through your use of the site, You expressly contract and consent to the operations of Day Trade Killers (including the moderator actions and omissions discussed above) and release Day Trade Killers, and its directors, officers, shareholders, employees, agents and affiliates from any liability, claim, loss, cost, expense, and any other damages arising from or relating to moderator statements (written or oral), actions and omissions, including real, simulated, or hypothetical trades and results. Trading in any security can result in immediate and substantial losses of the money invested. You should only invest funds that are not allocated for other purposes, such as retirement savings, student loans, mortgages, education, or debt reduction, and that you can afford to lose. Do not trade with money you can’t afford to lose.

ACTIVITIES OF DAY TRADE KILLERS PERSONNEL

Day Trade Killers, and its directors, officers, shareholders, employees, agents and affiliates, are active investors and traders of securities. Such parties may, but are not required to, purchase or sell any security, or engage in any investment strategy, contained in any data, content or information on the Site, or in the other products or services of Day Trade Killers. Such parties will purchase or sell securities, and engage in any investment strategies, in their sole discretion, at any time and without notice, and shall not, and are not required to disclose or otherwise notify you, or any other person or party, with respect to any such decisions or activities. For the avoidance of doubt, such parties may not always adhere to Day Trade Killers strategies and are not required to disclose or notify you, or any other person or party, with respect to any such decisions or activities. Day Trade Killers personnel adhere to their unique individual plans developed and implemented by them with or without Day Trade Killers, and experiences will not be duplicated and are not typical.

Day Trade Killers does not engage in, and its business and activities shall not constitute or be construed as, a business or activity with the purpose of creating a false or misleading appearance of active trading in any security, or a false or misleading appearance with respect to the market for such security, to effect any transaction in such security which involves no change in the beneficial ownership thereof, to enter an order or orders for the purchase of such security with the knowledge that an order or orders of substantially the same size, at substantially the same time, and at substantially the same price, for the sale of any such security, has been or will be entered by or for the same or different parties, or to enter any order or orders for the sale of any such security with the knowledge that an order or orders of substantially the same size, at substantially the same time, and at substantially the same price, for the purchase of such security, has been or will be entered by or for the same or different parties.

Day Trade Killers does not engage in, and its business and activities shall not constitute or be construed as, a business or activity to effect a series of transactions creating actual or apparent active trading in a security, or raising or depressing the price of such security, for the purpose of inducing the purchase or sale of such security by others.

Day Trade Killers does not engage in, and its business and activities shall not constitute or be construed as, a business or activity to effect a series of transactions for the purchase and/or sale of a security for the purpose of pegging, fixing, or stabilizing the price of such security in contravention of any law, rule or regulation.

You understand, acknowledge and agree that Day Trade Killers, and its directors, officers, shareholders, employees, agents and affiliates, engage in active trading of securities, but do not willfully participate in any activity described in the three preceding paragraphs. Accordingly, you hereby waive and release any and all claims, losses, damages, liabilities and any other costs and expenses (including attorneys’ fees), arising from or related to your purchase or sale of a security at a price that may have been affected by the business or activities of Day Trade Killers, or its directors, officers, shareholders, employees, agents or affiliates.

INVESTMENTS AND RESULTS

The purchase and sale of securities, futures, or commodities involve a high degree of risk and is speculative in nature. The purchase and sale of securities should only be conducted by persons who understand and accept the risks involved therewith and who have independently reviewed and determined their acceptance and suitability of these risks and the financial and tax consequences thereof. Only persons who are able to bear the risk of substantial or complete loss of funds should engage in the purchase and sale of securities, futures or commodities.

Day Trade Killers, and the content and information contained on the Site, and in other products and services of Day Trade Killers, do not indicate or guaranty any predictable, general, specific or other results. The purchase and sale of securities, and any other investment activity, involves a high degree of risk, and a number of factors could materially and adversely affect the results and lead to a substantial or complete loss of an investment.

As more fully set forth herein, Day Trade Killers, and its directors, officers, shareholders, employees, agents and affiliates, make no representation, warranty or guaranty as to the validity, adequacy, timeliness, accuracy, reliability or completeness of any data, content or information. You should independently analyze, review and confirm any such data, content or information.

Day Trade Killers may express or utilize testimonials or descriptions of past performance, but such items are not indicative of future results or performance, or any representation, warranty or guaranty that any result will be obtained by you. Your results may differ materially from those expressed or utilized by others due to a number of factors.

COMMODITY FUTURES TRADING COMMISSION RULE 4.41:  

Hypothetical performance results have many inherent limitations, some of which are described below. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown, in fact, there are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program. One of the limitations of hypothetical performance results is that they are generally prepared with the benefit of hindsight, in addition, hypothetical trading does not involve financial risk, and no hypothetical trading record can completely account for the impact of financial risk in actual trading. For example, the ability to withstand losses or adhere to a particular trading program in spite of trading losses are material points which can also adversely affect actual trading results. There are numerous other factors related to the markets in general or to the implementation of any specific trading program which cannot be fully accounted for in the preparation of hypothetical performance results and all of which can adversely affect actual trading results.

TESTIMONIALS DISCLAIMER

In accordance with 16 CFR Part 255 and Federal Trade Commission Guidelines concerning use of endorsements and testimonials in marketing and advertising, please be aware of the following:

• Endorsements, testimonials or descriptions of past performance from other customers or members are based upon their individual experiences and results with the Site, and the products and services of Day Trade Killers.  These results and performances are not typical, and you should not expect to achieve the same or similar results or performance, and your results and performance are likely to vary or differ materially. The endorsements, testimonials or descriptions of past performance are individual experiences, reflecting real life experiences of customers or members, and are not representative of the results and performances of all customers and members.
• Endorsements, testimonials or descriptions of past performance appearing on the Site were received pancekvia text, audio or video submission from customers or members. The endorsements, testimonials or descriptions of past performance (text, audio and/or video) are verbatim except for correction of grammatical or typing errors and editing for length. In other words, not the whole message received by the customer or member may be displayed, when it seemed lengthy or not all content seemed relevant for the general public. No endorsements, testimonials or descriptions of customers or members that appear on the Site involved payment or compensation therefor.

THIRD PARTY WEBSITES

The Site, and other products and services of Day Trade Killers, may contain links to other websites or applications. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party. Day Trade Killers has not reviewed all of the sites linked to or from the Site, or other products and services of Day Trade Killers,  and is not responsible for the content of any such linked website. We do not exercise control over third party websites. Your use of links to other websites is at your own risk. We are not responsible for third party sites linked from the Site, or other products and services of Day Trade Killers nor do we make any representation or warranties, express or implied, with respect to any such website, any content of such websites, or any products or services offered by any such websites, including but not limited to, accuracy, completeness, reliability, suitability, non-infringement, merchantability or fitness for a particular purpose.

LIMITATIONS OF LIABILITY

WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, DAY TRADE KILLERS  AND ITS DIRECTORS, OFFICERS, SHAREHOLDERS, EMPLOYEES, AGENTS AND AFFILIATES, SHALL NOT BE LIABLE TO YOU, UNDER ANY LEGAL OR EQUITABLE THEORY, FOR (A) ANY CONSEQUENTIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, SPECIAL OR INDIRECT DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION LOST PROFITS, REVENUES AND BUSINESS, ARISING OUT OF, UNDER OR RELATING TO THESE TERMS AND CONDITIONS, YOUR USE OF THE SITE OR OTHERWISE RELATED TO OR ARISING FROM THE PRODUCTS OR SERVICES OF DAY TRADE KILLERS  OR (B) ANY DAMAGES OF ANY KIND ARISING OUT OF, UNDER OR RELATING TO THE SITE OR OTHERWISE RELATED TO OR ARISING FROM THE PRODUCTS OR SERVICES OF DAY TRADE KILLERS, IN EXCESS OF THREE TIMES THE MOST RECENT MONTHLY FEE PAID BY YOU IN CONNECTION WITH THE SITE, IF ANY, OR $250, WHICHEVER AMOUNT IS GREATER.

THIS LIMITATION OF LIABILITY SHALL APPLY REGARDLESS OF WHETHER THE LIMITED REMEDIES PROVIDED HEREIN FAIL OF THEIR ESSENTIAL PURPOSE, AND SHALL NOT APPLY TO ANY DAMAGE TO YOU INTENTIONALLY CAUSED BY DAY TRADE KILLERS IN VIOLATION OF THESE TERMS AND CONDITIONS OR APPLICABLE LAW, OR AS OTHERWISE MANDATED BY APPLICABLE LAW THAT CANNOT BE DISCLAIMED BY THESE TERMS AND CONDITIONS.
INDEMNIFICATION

You shall, and hereby agree to, indemnify and hold harmless, Day Trade Killers and its officers, directors, shareholders, employees, agents and affiliates, from any and all claims, losses, damages, liabilities and any other costs and expenses (including attorneys’ fees), arising from or related to your (i) breach of a representation or warranty contained in these Terms and Conditions, (ii) breach of, or failure to comply with, any term contained in these Terms and Conditions, (iii) use of the Site or any products or services of Day Trade Killers, or (iv) use of, access to or other activity engaged in, on, through, related to or in connection with the Site.

PRIVACY AND PERSONAL INFORMATION

Day Trade Killers shall have the right to use and disclose any information provided by you through the Site, or other products or services of Day Trade Killers (including but not limited to information provided through e-mail) or made available through your use of the Site, for any lawful purpose, unless you indicate otherwise in accordance with the policies and procedures therefor of Day Trade Killers.  In no event shall you be entitled to any compensation for the use of any of such information. Please see the Privacy Policy for further details.

MODIFICATIONS

Day Trade Killers reserves the right to revise these Terms and Conditions at any time without notice. By using the Site, you are agreeing to be bound by the then-current version of these Terms and Conditions, and your continued use of the Site reaffirms your agreement to the then-current Terms and Conditions. You agree to consult the Site regularly for up-to-date information about these Terms and Conditions and the Privacy Policy.
• Day Trade Killers may make changes to the Site, and the other products and services of Day Trade Killers, at any time without notice. Day Trade Killers does not, however, make any commitment to update the Site, and the other products and services of Day Trade Killers.

GOVERNING LAW

Any claim under these Terms and Conditions or otherwise related to the Site or Day Trade Killers shall be governed by the laws of the State of California without regard to its conflict of law provisions, and shall be exclusively resolved by a state or federal court located in California. You agree to submit to the personal jurisdiction of the courts located within California, or another location of Day Trade Killers choosing, for the purpose of litigating all such claims. Notwithstanding the above, you agree that Day Trade Killers shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction. Except as otherwise provided herein, you agree that any controversy or claim, whether at law or equity, arising out of or related to the provision of services or materials by Day Trade Killers, regardless of the date of accrual of such dispute, shall be resolved in its entirety by individual (not class-wide nor collective) binding arbitration.

The Site, and the other products and services of Day Trade Killers, are solely directed to and intended for individuals residing in the United States. Those who choose to access and use the Site, and the other products and services of Day Trade Killers, from other locations do so at their own risk, and are responsible for compliance with all laws, rules and regulations applicable thereto. Day Trade Killers reserves the right to limit the availability of the Site, and any other products or services of Day Trade Killers, to any person, geographic area, or jurisdiction, in any manner and at any time, in its sole discretion.

SEVERABILITY

If any provision of these Terms and Conditions is found by a court of competent jurisdiction or arbitrator to be illegal, void, or unenforceable, the unenforceable provision will be modified so as to render it enforceable and effective to the maximum extent possible in order to effect the intention of the provision; and if a court or arbitrator finds the modified provision invalid, illegal, void or unenforceable, the validity, legality and enforceability of the remaining provisions of these Terms and Conditions will not be affected in any way.

ENTIRE AGREEMENT

You agree that these Terms and Conditions constitute the entire, complete and exclusive agreement between you and us regarding the Site and the products and services of Day Trade Killers, and supersedes all prior agreements and understandings, whether written or oral, or whether established by custom, practice, policy or precedent, with respect to the subject matter of these Terms and Conditions. The provisions of these Terms and Conditions shall survive any termination thereof indefinitely.

WAIVERS

Our failure to act with respect to a breach of these Terms and Conditions by you or others does not waive our right to act with respect to that breach or subsequent similar or other breaches.

QUESTIONS?

Questions about these Terms and Conditions, billing or any other matters should be addressed to hello@daytradekillers.com.

IF YOU DO NOT AGREE WITH ANY TERM OR PROVISION OF THESE TERMS AND CONDITIONS, PLEASE EXIT THE SITE IMMEDIATELY. PLEASE BE ADVISED THAT YOUR CONTINUED USE OF THIS SITE OR THE PRODUCTS OR INFORMATION PROVIDED THEREBY SHALL INDICATE YOUR CONSENT AND AGREEMENT TO THESE TERMS AND CONDITIONS.</p>
  
        </div>
    </Layout>
  )
}

export default Terms